Add upgrade vote command

diff --git a/thornode/templates/configmap.yaml b/thornode/templates/configmap.yaml
--- a/thornode/templates/configmap.yaml
+++ b/thornode/templates/configmap.yaml
@@ -61,6 +61,28 @@ data:
 
     printf "%s\n%s\n" "$SIGNER_PASSWD" "$SIGNER_PASSWD" | thornode tx thorchain mimir --from "$SIGNER_NAME" --keyring-backend file --chain-id "$CHAIN_ID" --yes --gas auto --gas-adjustment 2 --node "tcp://localhost:$THORNODE_SERVICE_PORT_RPC" -- "$1" "$2"
 
+  upgrade-vote.sh: |
+    #!/bin/sh
+
+    if [ -z "$1" ] || [ -z "$2" ]; then
+      echo "Usage: upgrade-vote.sh <proposal-name> <yes|no>"
+      exit 1
+    fi
+
+    case "$2" in
+        [yY][eE][sS]|[yY]) 
+            action="approve-upgrade"
+            ;;
+        [nN][oO]|[nN])
+            action="reject-upgrade"
+            ;;
+        *)
+           echo "Invalid vote: $2, must be 'yes' or 'no'" 
+            ;;
+    esac
+
+    printf "%s\n%s\n" "$SIGNER_PASSWD" "$SIGNER_PASSWD" | thornode tx thorchain "$action" "$1" --from "$SIGNER_NAME" --keyring-backend file --chain-id "$CHAIN_ID" --yes --gas auto --gas-adjustment 2 --node "tcp://localhost:$THORNODE_SERVICE_PORT_RPC"
+
   ban.sh: |
     #!/bin/sh
 
